apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

configMapGenerator:
  - name: backend-config
    literals:
      - ENVIRONMENT=dev
      - ALLOWED_ORIGINS=*
      - LOG_LEVEL=debug

images:
  - name: ACCOUNT.dkr.ecr.REGION.amazonaws.com/backend:latest
    newName: 157611948522.dkr.ecr.us-east-1.amazonaws.com/ulises-backend
    newTag: latest
  - name: ACCOUNT.dkr.ecr.REGION.amazonaws.com/frontend:latest
    newName: 157611948522.dkr.ecr.us-east-1.amazonaws.com/ulises-frontend
    newTag: latest